### ISSUE TITLE
GET request on the GAR api when updating an object

### ISSUE THREAD

**Issue by ThomSawyer** [briefmnews/django-gar#2]
This would allow to see immediately if the subscription is in the GAR without hitting the save button

**Comment by ThomSawyer** [comment]
Done

**Comment by eespanel** [comment]
I trust you.

**Comment by ThomSawyer** [comment]
You can see it in action here: https://www.brief.me/bfme_bo/django_gar/garinstitution/123/change/?_changelist_filters=p%3D2
